spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2hycXRPUEpBODZ2ZzZLeCsKalBsckw0OWhJNXJXZFFFY0ZVRkRVVERXU0N5aFJBTkNBQVNKUCtTZk1YaEpCekF5cUdpNDNoQUc0M25PaEhEZApNS1pweHZGRHJVaS9FZCtrUHladS9nWEc4TEFEcnYyakxnTHlOY3gvZHA3dFpJUlhFdUg2ajVVUwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JR0lDQm9nQXdJQkFnSVFXSmVnVGZOL3pIYU83ck1zOW10eWURUUtQmdncWhrak9QUVFEQWpDQmhURWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1TMHdLd1lEVlFRTERDUjJZV3hsYm5ScApia0IyWVd4bGJuUnBiaTFVYUdsdWExQmhaQzFGTVRRdFIyVnVMVFV4TkRBeUJnTlZCQU1NSzIxclkyVnlkQ0IyCllXeGxiblJwYmtCMllXeGxiblJwYmkxVWFHbHVhMUJoWkMxRk1UUXRSMlZ1TFRVd0hoY05Nall3TkRFMU1EY3kKTnpBM1doY05Namd3TnpFMU1EY3lOekEzV2pCWU1TY3dKUVlEVlFRS0V4NXRhMk5sY25RZ1pHVjJaV3h2Y0cxbApiblFnWTJWeWRHbG1hV05oZEdVeExUQXJCZ05WQkFzTUpIWmhiR1Z1ZEdsdVFIWmhiR1Z1ZEdsdUxWUm9hVzVyClVHRmtMVVV4TkMxSFpXNHROVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSWsvNUo4eGVFa0gKTURLb2FMamVFQWJqZWM2RWNOMHdwbW5HOFVPdFNMOFIzNlEvSm03K0JjYndzQU91L2FNdUF2STF6SDkybnUxawpoRmNTNGZxUGxSS2paREJpTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNECkFUQWZCZ05WSFNNRUdEQVdnQlJzNTBCTFZBOGVuTytLaVN4bHBnYUZTMTgydXpBYUJnTlZIUkVFRXpBUmdnOXMKYjJOaGJDNHdlR1JpWlM1a1pYWXdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdZTlNFbGl1bHRhZjlGSGlsRys0SQpLR3FUYlBISUVNK2FsMkY4c0c3UkIvVUNJSDNSLy83SkVzK1EvaXZhRTloMDREQmJZeStDK28vekEwTmdXNk1zCkZ4czEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNVRENDQWZhZ0F3SUJBZ0lSQUtRa1JhaWNmdDRyR3dxVVc0dnZSQlF3Q2dZSUtvWkl6ajBFQXdJd2dZVXgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURXRNQ3NHQTFVRUN3d2tkbUZzWlc1MAphVzVBZG1Gc1pXNTBhVzR0VkdocGJtdFFZV1F0UlRFMExVZGxiaTAxTVRRd01nWURWUVFEREN0dGEyTmxjblFnCmRtRnNaVzUwYVc1QWRtRnNaVzUwYVc0dFZHaHBibXRRWVdRdFJURTBMVWRsYmkwMU1CNFhEVEkyTURReE5UQTMKTWpjd04xb1hEVE0yTURReE5UQTNNamN3TjFvd2dZVXhIakFjQmdOVkJBb1RGVzFyWTJWeWRDQmtaWFpsYkc5dwpiV1Z1ZENCRFFURXRNQ3NHQTFVRUN3d2tkbUZzWlc1MGFXNUFkbUZzWlc1MGFXNHRWR2hwYm10UVlXUXRSVEUwCkxVZGxiaTAxTVRRd01nWURWUVFEREN0dGEyTmxjblFnZG1Gc1pXNTBhVzVBZG1Gc1pXNTBhVzR0VkdocGJtdFEKWVdRdFJURTBMVWRsYmkwMU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRTNoVUhnN0Y2SVg1cgpkUmlqWFNpWFBLUUpNK2xGWjFKV0lVaEN3MmpJVlVUVXlFc1hEWEE2VDVvMW44eGhWaUR3bEtPcXMwQjMwZWN5Clo5dVhtNmdFQ3FORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXcKSFFZRFZSME9CQllFRkd6blFFdFVEeDZjNzRxSkxHV21Cb1ZMWHphN01Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQwpJQk5LTks3Rlg2cDR1QXlOSllxZmw2WDF3Q3ZtSU5BU1FOY3BTdWo2eHhoVUFpRUFrdVdpL01XZXNhb0hoYzhBCjJRY3ZYYm1nTStscmtPUUw5YXRJQTJDWGVkbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

server:
  port: 8443
  ssl:
    bundle: web
  servlet:
    session:
      cookie:
        same-site: strict