name: security

on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à minuit (Requis pour le "Daily")
  workflow_dispatch:

permissions:
  # Required to upload SARIF file to CodeQL.
  actions: read
  # Require writing security events to upload SARIF file
  security-events: write
  # to fetch code (actions/checkout)
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
          generateSarif: "1"
        continue-on-error: true

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep
        continue-on-error: true
