name: PR Security Check

# Se déclenche uniquement lors d'une Pull Request
on: 
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1 : Analyse des dépendances (Differential OSV-Scanner)
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code (After PR)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run OSV Scanner (After PR)
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.0
        with:
          scan-args: |-
            --format sarif
            --output osv-after.sarif
            ./
        continue-on-error: true

      - name: Checkout baseline commit
        run: git checkout ${{ github.event.pull_request.base.sha }}

      - name: Run OSV Scanner (Before PR)
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.0
        with:
          scan-args: |-
            --format sarif
            --output osv-before.sarif
            ./
        continue-on-error: true

      - name: Compare OSV analysis
        uses: google/osv-scanner-action/osv-reporter-action@v1.9.0
        with:
          scan-args: |-
            --new osv-after.sarif
            --old osv-before.sarif
            --output osv-diff.sarif

      - name: Save OSV differential report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: osv-differential-report
          path: osv-diff.sarif
