name: security

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  DependenciesAnalysis:
    name: DependenciesAnalysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Upload OSV SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysisFull.sarif
          category: osv-scanner

  SourceCodeAnalysis:
    name: SourceCodeAnalysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:0a014c440663e466a79401c24e0cc8c63e18975cd9eb82dca62d0826b41a359a
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep \
            --config .semgrep/ \
            --sarif \
            --output SourceCodeAnalysisFull.sarif \
            .
        continue-on-error: true

      - name: Upload Semgrep SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: SourceCodeAnalysisFull.sarif
          category: semgrep
